# https://docs.microsoft.com/azure/devops/pipelines/languages/python
# based on pipelines of https://github.com/ltalirz/aiida-zeopp
trigger:
- aiida1

variables:


  TEST_AIIDA_BACKEND: django
  DB_HOST: postgres

jobs:
- job:                    test
  pool:
    vmImage:              'Ubuntu-16.04'
  strategy:
    matrix:
#      Python27:
#        python.version:   '2.7'
      Python36:
        python.version:   '3.6'
    maxParallel:          4
  steps:
  - script: docker build -t test .
    displayName:          'Build Docker image'
  - script:               docker run test bash  /home/aiida/code/aiida-ddec/aiida_ddec/tests/run_test.sh
    displayName:          'Run pytest'

  - task:                 PublishTestResults@2
    inputs:
      testResultsFiles:   'test-results.xml'
      testRunTitle:       'Python $(python.version)'
    condition:            succeededOrFailed()


- job:                    pre_commit
  strategy:
    matrix:
#      Python27:
#        python.version:   '2.7'
      Python36:
        python.version:   '3.6'
    maxParallel:          4
  steps:
  - template:             .ci/azure-templates/pip-steps.yml
  - script:               pre-commit install; SKIP=yapf pre-commit run --all-files || ( git status --short; git diff ; exit 1 );
    displayName:          'Run pre-commit check'
